language: csharp
sudo: true
mono:
  - beta
env:
  - MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/api/v2/
os:
  - linux
  - osx
before_script:
  - chmod ugo+x build.sh
script:
  - ./build.sh --quiet verify
